// Assets

// Custom icons

export const dashboardData = {
  id: 1,
  name: "Arney Walczak",
  role: "GOP",
  email: "arney.walczak@sportsschool.edu.sg",
  contactNo: "97450148",
  passLimit: "2",
  loanLimit: "2",
  isActive: true,
  created: "1/2/2021",
};

export const loanData = [
  {
    id: 1,
    place: "Singapore Zoo",
    noOfPass: "1",
    date: "23/12/2022",
    status: "Success",
    cardNumbers: ["0123456789012345678900", "9123456789012345678900"],
  },
  {
    id: 2,
    place: "Gardens By The Bay",
    noOfPass: "2",
    date: "08/12/2022",
    status: "Pending",
    cardNumbers: ["0123456789012345678900", "9123456789012345678900"],
  },
];

export const loanHistoryData = [
  {
    id: 4,
    place: "Singapore Zoo",
    noOfPass: "1",
    date: "23/12/2022",
    status: "Success",
  },
  {
    id: 3,
    place: "Gardens By The Bay",
    noOfPass: "2",
    date: "08/12/2022",
    status: "Pending",
  },
  {
    id: 2,
    place: "Art Science Museum",
    noOfPass: "2",
    date: "10/10/2022",
    status: "Returned",
  },
  {
    id: 1,
    place: "Duck Tours",
    noOfPass: "2",
    date: "01/10/2022",
    status: "Returned",
  },
];

export const corporatePassData = [
  {
    id: 1,
    name: "Singapore Zoo",
    type: "Digital",
    replacementFee: "50.00",
    cardNumber: "0123456789012345678900",
    noOfCards: "2",
    borrower: "Arney Walczak",
  },
  {
    id: 2,
    name: "Singapore Zoo",
    type: "Physical",
    replacementFee: "50.00",
    cardNumber: "9123456789012345678900",
    noOfCards: "2",
    borrower: "Arney Walczak",
  },
  {
    id: 3,
    name: "River Wonders",
    type: "Digital",
    replacementFee: "50.00",
    cardNumber: "5124413789011435675931",
    noOfCards: "4",
    borrower: "",
  },
  {
    id: 4,
    name: "Gardens By The Bay",
    type: "Digital",
    replacementFee: "50.00",
    cardNumber: "1346512324533184853234",
    noOfCards: "2",
    borrower: "Daryl Feedome",
  },
  {
    id: 5,
    name: "Art Science Museum",
    type: "Physical",
    replacementFee: "50.00",
    cardNumber: "3456134954395345984549",
    noOfCards: "2",
    borrower: "Ambrosio Inglefield",
  },
  {
    id: 6,
    name: "Duck Tours",
    type: "Physical",
    replacementFee: "50.00",
    cardNumber: "1342539634313819485424",
    noOfCards: "2",
    borrower: "Ulrick Grout",
  },
];

export const templatesData = [
  {
    id: 1,
    name: "Singapore Zoo",
    type: "Digital",
  },
  {
    id: 3,
    name: "River Wonders",
    type: "Digital",
  },
  {
    id: 4,
    name: "Gardens By The Bay",
    type: "Digital",
  },
  {
    id: 5,
    name: "Art Science Museum",
    type: "Physical",
  },
  {
    id: 6,
    name: "Duck Tours",
    type: "Physical",
  },
];

export const usersData = [
  {
    id: 1,
    name: "Admin",
    role: "Admin",
    email: "admin@sportsschool.edu.sg",
    contactNo: "98765432",
    passLimit: "5",
    loanLimit: "5",
    isActive: true,
    created: "01/01/2019",
  },
  {
    id: 2,
    name: "Arney Walczak",
    role: "GOP",
    email: "arney.walczak@sportsschool.edu.sg",
    contactNo: "97450148",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "1/2/2021",
  },
  {
    id: 3,
    name: "Iolanthe Klugman",
    role: "Borrower",
    email: "iolanthe.klugman@sportsschool.edu.sg",
    contactNo: "90454822",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "9/9/2021",
  },
  {
    id: 4,
    name: "Daryl Feedome",
    role: "Borrower",
    email: "daryl.feedome@sportsschool.edu.sg",
    contactNo: "91541345",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "9/13/2021",
  },
  {
    id: 5,
    name: "Dorris Meacher",
    role: "Borrower",
    email: "dorris.meacher@sportsschool.edu.sg",
    contactNo: "98135471",
    passLimit: "2",
    loanLimit: "2",
    isActive: false,
    created: "2/13/2021",
  },
  {
    id: 6,
    name: "Ambrosio Inglefield",
    role: "Borrower",
    email: "ambrosio.inglefield@sportsschool.edu.sg",
    contactNo: "90045813",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "1/2/2021",
  },
  {
    id: 7,
    name: "Latrina Ricciardi",
    role: "Borrower",
    email: "latrina.ricciardi@nysi.org.sg",
    contactNo: "90458139",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "1/13/2021",
  },
  {
    id: 8,
    name: "Ulrick Grout",
    role: "Borrower",
    email: "ulrick.grout@nysi.org.sg",
    contactNo: "90135841",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "12/25/2020",
  },
  {
    id: 9,
    name: "Nadine Lodo",
    role: "Borrower",
    email: "nadine.lodo@nysi.org.sg",
    contactNo: "90415893",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "11/4/2020",
  },
  {
    id: 10,
    name: "Allene Silkston",
    role: "Borrower",
    email: "allene.silkston@sportsschool.edu.sg",
    contactNo: "98135719",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "4/7/2021",
  },
  {
    id: 11,
    name: "Linet Howles",
    role: "Borrower",
    email: "linet.howles@nysi.org.sg",
    contactNo: "90136849",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "11/26/2020",
  },
  {
    id: 12,
    name: "Mathe Scrange",
    role: "Borrower",
    email: "mathe.scrange@nysi.org.sg",
    contactNo: "90781458",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "6/27/2021",
  },
  {
    id: 13,
    name: "Elsy Kobierzycki",
    role: "Borrower",
    email: "elsy.kobierzycki@sportsschool.edu.sg",
    contactNo: "90058329",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "5/1/2021",
  },
  {
    id: 14,
    name: "Asa Willson",
    role: "Borrower",
    email: "asa.willson@sportsschool.edu.sg",
    contactNo: "90417491",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "4/15/2021",
  },
  {
    id: 15,
    name: "Dallas Deinhardt",
    role: "Borrower",
    email: "dallas.deinhardt@sportsschool.edu.sg",
    contactNo: "90135719",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "9/29/2021",
  },
  {
    id: 16,
    name: "Jessee Jendrassik",
    role: "Borrower",
    email: "jessee.jendrassik@sportsschool.edu.sg",
    contactNo: "90145719",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "1/4/2021",
  },
  {
    id: 17,
    name: "Care Olford",
    role: "Borrower",
    email: "care.olford@sportsschool.edu.sg",
    contactNo: "90134718",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "12/15/2020",
  },
  {
    id: 18,
    name: "Jay Charville",
    role: "Borrower",
    email: "jay.charville@sportsschool.edu.sg",
    contactNo: "90134581",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "4/15/2021",
  },
  {
    id: 19,
    name: "Jesse Lasty",
    role: "Borrower",
    email: "jesse.lasty@sportsschool.edu.sg",
    contactNo: "90451348",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "8/11/2021",
  },
  {
    id: 20,
    name: "Ginelle De Francisci",
    role: "Borrower",
    email: "ginelle.francisci@sportsschool.edu.sg",
    contactNo: "98134574",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "5/11/2021",
  },
  {
    id: 21,
    name: "Rozele Siaskowski",
    role: "Borrower",
    email: "rozele.siaskowski@sportsschool.edu.sg",
    contactNo: "98001348",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "11/30/2020",
  },
  {
    id: 22,
    name: "Mata Bonner",
    role: "Borrower",
    email: "mata.bonner@sportsschool.edu.sg",
    contactNo: "98013591",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "9/17/2021",
  },
  {
    id: 23,
    name: "Aleen Casina",
    role: "Borrower",
    email: "aleen.casina@sportsschool.edu.sg",
    contactNo: "97031348",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "5/16/2021",
  },
  {
    id: 24,
    name: "Diahann Coorington",
    role: "Borrower",
    email: "diahann.coorington@sportsschool.edu.sg",
    contactNo: "90123571",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "4/17/2021",
  },
  {
    id: 25,
    name: "Orazio Atling",
    role: "Borrower",
    email: "orazio.atling@sportsschool.edu.sg",
    contactNo: "90123581",
    passLimit: "2",
    loanLimit: "2",
    isActive: true,
    created: "7/3/2021",
  },
];

export const issuanceData = [
  {
    id: 8,
    name: "Care Olford",
    email: "care.olford@sportsschool.edu.sg",
    attraction: "Duck Tours",
    collectionDate: "-",
    returnDate: "-",
    status: "Pending",
  },
  {
    id: 7,
    name: "Orazio Atling",
    email: "orazio.atling@sportsschool.edu.sg",
    attraction: "Gardens By The Bay",
    collectionDate: "-",
    returnDate: "-",
    status: "Available",
  },
  {
    id: 6,
    name: "Latrina Ricciardi",
    email: "latrina.ricciardi@nysi.org.sg",
    attraction: "River Wonders",
    collectionDate: "07/10/2022",
    returnDate: "-",
    status: "Issued",
  },
  {
    id: 5,
    name: "Mata Bonner",
    email: "mata.bonner@sportsschool.edu.sg",
    attraction: "Singapore Zoo",
    collectionDate: "06/10/2022",
    returnDate: "-",
    status: "Issued",
  },
  {
    id: 4,
    name: "Elsy Kobierzycki",
    email: "elsy.kobierzycki@sportsschool.edu.sg",
    attraction: "River Wonders",
    collectionDate: "05/10/2022",
    returnDate: "-",
    status: "Issued",
  },
  {
    id: 3,
    name: "Aleen Casina",
    email: "aleen.casina@sportsschool.edu.sg",
    attraction: "Gardens By The Bay",
    collectionDate: "19/09/2022",
    returnDate: "-",
    status: "Lost",
  },
  {
    id: 2,
    name: "Mata Bonner",
    email: "mata.bonner@sportsschool.edu.sg",
    attraction: "Art Science Museum",
    collectionDate: "03/08/2022",
    returnDate: "10/10/2022",
    status: "Returned",
  },
  {
    id: 1,
    name: "Arney Walczak",
    email: "arney.walczak@sportsschool.edu.sg",
    attraction: "Duck Tours",
    collectionDate: "01/05/2022",
    returnDate: "01/10/2022",
    status: "Returned",
  },
];

export const pdfTemplate =
  "<p>Dear Borrower,</p><br/><p>We are pleased to inform that your booking to Singapore Zoo is confirmed as follows: </p><br/><p>Date of Visit: Saturday, 12 February 2022 (1 day only)</p><p>Membership ID: 1234567890</p><br/><p>For any change in visit date, you are required to cancel your booking (at least 1 day before) and to submit a new booking in the system.</p><br/><p>Attached is the authorisation letter to Singapore Zoo. Please check that the details are accurate.</p><br/><p>Please take note of the following for your visit to Singapore Zoo:</p><ul><li>Present this email confirmation to the General Office to collect the membership card(s).</li><li>Collect the membership card(s) from the General Office one day before your visit date and return the membership card(s) by 9am the next working day after your visit.</li><li>Present the membership card(s), the authorisation letter and your staff pass at the entrance of Singapore Zoo</li><li>Entry is strictly based on the membership card(s) and the authorisation letter.</li><li>Your presence is required on the day of visit. Entry will be denied without staff's presence.</li><li>Your booking is non-transferable.</li><li>Visit date is strictly based on the date stated in this email and the authorisation letter.</li><li>Staff found abusing the membership(s) will be subject to disciplinary actions.</li></ul><br/><p>Enjoy your visit to Singapore Zoo!</p><br/><p>Warm regards</p><p>HR Department</p>";
